---
# JupyterLab Installation auf node0
#
# Verwendung:
#   ansible-playbook -i inventory.yml jupyter.yml
#
# JupyterLab ist erreichbar unter: http://node0.cloud.local:8888

- name: Install JupyterLab on monitoring node
  hosts: monitoring
  vars:
    jupyter_user: cloudadmin
    jupyter_home: /opt/jupyter
    jupyter_data: /data/jupyter
    jupyter_port: 8888
    spark_home: /opt/spark
    force_notebooks: "{{ force | default(false) | bool }}"

  tasks:
    # ============================================================
    # System-Pakete
    # ============================================================
    - name: Install system dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-venv
          - python3-dev
          - build-essential
        state: present
        update_cache: yes

    # ============================================================
    # Verzeichnisse
    # ============================================================
    - name: Create Jupyter directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0755'
      loop:
        - "{{ jupyter_home }}"
        - "{{ jupyter_data }}"
        - "{{ jupyter_data }}/notebooks"
        - "/home/{{ jupyter_user }}/.jupyter"

    # ============================================================
    # Python Virtual Environment
    # ============================================================
    - name: Create Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv {{ jupyter_home }}/venv
        creates: "{{ jupyter_home }}/venv/bin/activate"
      become_user: "{{ jupyter_user }}"

    - name: Install Python packages
      ansible.builtin.pip:
        name:
          - jupyterlab
          - notebook
          - "pyspark=={{ spark_version }}"
          - pandas
          - pyarrow
          - numpy
          - matplotlib
          - pysolr
          - requests
        virtualenv: "{{ jupyter_home }}/venv"
        state: present
      become_user: "{{ jupyter_user }}"

    # ============================================================
    # Spark Installation (fuer SPARK_HOME)
    # ============================================================
    - name: Check if Spark is installed
      ansible.builtin.stat:
        path: "{{ spark_home }}/bin/spark-submit"
      register: spark_installed

    - name: Download Spark
      ansible.builtin.get_url:
        url: "https://archive.apache.org/dist/spark/spark-{{ spark_version }}/spark-{{ spark_version }}-bin-hadoop3.tgz"
        dest: "/tmp/spark-{{ spark_version }}.tgz"
        mode: '0644'
      when: not spark_installed.stat.exists

    - name: Extract Spark
      ansible.builtin.unarchive:
        src: "/tmp/spark-{{ spark_version }}.tgz"
        dest: "{{ spark_home }}"
        remote_src: yes
        extra_opts: ['--strip-components=1']
        creates: "{{ spark_home }}/bin/spark-submit"
      when: not spark_installed.stat.exists

    - name: Set Spark directory ownership
      ansible.builtin.file:
        path: "{{ spark_home }}"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        recurse: yes
        state: directory

    # ============================================================
    # Konfiguration
    # ============================================================
    - name: Deploy JupyterLab configuration
      ansible.builtin.template:
        src: templates/jupyter/jupyter_lab_config.py.j2
        dest: "/home/{{ jupyter_user }}/.jupyter/jupyter_lab_config.py"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'

    - name: Deploy systemd service
      ansible.builtin.template:
        src: templates/jupyter/jupyterlab.service.j2
        dest: /etc/systemd/system/jupyterlab.service
        mode: '0644'
      notify: Restart JupyterLab

    # ============================================================
    # Service starten
    # ============================================================
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start JupyterLab
      ansible.builtin.systemd:
        name: jupyterlab
        enabled: yes
        state: started

    # ============================================================
    # Demo Notebooks
    # ============================================================
    - name: Deploy Cluster Dashboard notebook
      ansible.builtin.template:
        src: templates/jupyter/00-cluster-dashboard.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/00-cluster-dashboard.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: "{{ force_notebooks }}"  # Use -e "force=true" to overwrite
      tags: notebooks

    - name: Deploy Spark example notebook
      ansible.builtin.template:
        src: templates/jupyter/01-spark-example.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/01-spark-example.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: "{{ force_notebooks }}"  # Use -e "force=true" to overwrite
      tags: notebooks

    - name: Deploy Solr example notebook
      ansible.builtin.template:
        src: templates/jupyter/02-solr-example.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/02-solr-example.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: "{{ force_notebooks }}"  # Use -e "force=true" to overwrite
      tags: notebooks

    - name: Deploy NYC Taxi analysis notebook
      ansible.builtin.template:
        src: templates/jupyter/03-nyc-taxi-analysis.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/03-nyc-taxi-analysis.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: "{{ force_notebooks }}"  # Use -e "force=true" to overwrite
      tags: notebooks

    - name: Deploy Lambda Architecture notebook
      ansible.builtin.template:
        src: templates/jupyter/04-lambda-architecture.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/04-lambda-architecture.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: "{{ force_notebooks }}"  # Use -e "force=true" to overwrite
      tags: notebooks

    - name: Deploy Drill-Down Architecture notebook
      ansible.builtin.template:
        src: templates/jupyter/05-drilldown-architecture.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/05-drilldown-architecture.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: "{{ force_notebooks }}"  # Use -e "force=true" to overwrite
      tags: notebooks

    - name: Deploy Prometheus Timeseries Analysis notebook
      ansible.builtin.template:
        src: templates/jupyter/06-prometheus-timeseries-analysis.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/06-prometheus-timeseries-analysis.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: "{{ force_notebooks }}"  # Use -e "force=true" to overwrite
      tags: notebooks

    - name: Deploy Software EKG Timeseries Analysis notebook
      ansible.builtin.template:
        src: templates/jupyter/07-software-ekg-timeseries-analysis.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/07-software-ekg-timeseries-analysis.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: "{{ force_notebooks }}"  # Use -e "force=true" to overwrite
      tags: notebooks

    - name: Create datasets directory
      ansible.builtin.file:
        path: "{{ jupyter_data }}/datasets"
        state: directory
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0755'

    # ============================================================
    # Healthcheck
    # ============================================================
    - name: Wait for JupyterLab to be ready
      ansible.builtin.wait_for:
        port: "{{ jupyter_port }}"
        delay: 3
        timeout: 60

    - name: Display access information
      ansible.builtin.debug:
        msg: |
          ============================================
          JupyterLab erfolgreich installiert!
          
          URL: http://node0.cloud.local:{{ jupyter_port }}
          Notebooks: {{ jupyter_data }}/notebooks
          
          Spark Master: spark://node0.cloud.local:7077
          ============================================

  handlers:
    - name: Restart JupyterLab
      ansible.builtin.systemd:
        name: jupyterlab
        state: restarted
        daemon_reload: yes
