---
# JupyterLab Installation auf node0
#
# Verwendung:
#   ansible-playbook -i inventory.yml jupyter.yml
#
# JupyterLab ist erreichbar unter: http://node0.cloud.local:8888

- name: Install JupyterLab on monitoring node
  hosts: monitoring
  vars:
    jupyter_user: cloudadmin
    jupyter_home: /opt/jupyter
    jupyter_data: /data/jupyter
    jupyter_port: 8888
    spark_home: /opt/spark

  tasks:
    # ============================================================
    # System-Pakete
    # ============================================================
    - name: Install system dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-venv
          - python3-dev
          - build-essential
        state: present
        update_cache: yes

    # ============================================================
    # Verzeichnisse
    # ============================================================
    - name: Create Jupyter directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0755'
      loop:
        - "{{ jupyter_home }}"
        - "{{ jupyter_data }}"
        - "{{ jupyter_data }}/notebooks"
        - "/home/{{ jupyter_user }}/.jupyter"

    # ============================================================
    # Python Virtual Environment
    # ============================================================
    - name: Create Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv {{ jupyter_home }}/venv
        creates: "{{ jupyter_home }}/venv/bin/activate"
      become_user: "{{ jupyter_user }}"

    - name: Install Python packages
      ansible.builtin.pip:
        name:
          - jupyterlab
          - notebook
          - "pyspark=={{ spark_version }}"
          - pandas
          - pyarrow
          - numpy
          - matplotlib
          - pysolr
          - requests
        virtualenv: "{{ jupyter_home }}/venv"
        state: present
      become_user: "{{ jupyter_user }}"

    # ============================================================
    # Konfiguration
    # ============================================================
    - name: Deploy JupyterLab configuration
      ansible.builtin.template:
        src: templates/jupyter/jupyter_lab_config.py.j2
        dest: "/home/{{ jupyter_user }}/.jupyter/jupyter_lab_config.py"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'

    - name: Deploy systemd service
      ansible.builtin.template:
        src: templates/jupyter/jupyterlab.service.j2
        dest: /etc/systemd/system/jupyterlab.service
        mode: '0644'
      notify: Restart JupyterLab

    # ============================================================
    # Service starten
    # ============================================================
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start JupyterLab
      ansible.builtin.systemd:
        name: jupyterlab
        enabled: yes
        state: started

    # ============================================================
    # Demo Notebooks
    # ============================================================
    - name: Deploy Spark example notebook
      ansible.builtin.template:
        src: templates/jupyter/01-spark-example.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/01-spark-example.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: no  # Don't overwrite if user modified

    - name: Deploy Solr example notebook
      ansible.builtin.template:
        src: templates/jupyter/02-solr-example.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/02-solr-example.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: no  # Don't overwrite if user modified

    - name: Deploy NYC Taxi analysis notebook
      ansible.builtin.template:
        src: templates/jupyter/03-nyc-taxi-analysis.ipynb.j2
        dest: "{{ jupyter_data }}/notebooks/03-nyc-taxi-analysis.ipynb"
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0644'
        force: no  # Don't overwrite if user modified

    - name: Create datasets directory
      ansible.builtin.file:
        path: "{{ jupyter_data }}/datasets"
        state: directory
        owner: "{{ jupyter_user }}"
        group: "{{ jupyter_user }}"
        mode: '0755'

    # ============================================================
    # Healthcheck
    # ============================================================
    - name: Wait for JupyterLab to be ready
      ansible.builtin.wait_for:
        port: "{{ jupyter_port }}"
        delay: 3
        timeout: 60

    - name: Display access information
      ansible.builtin.debug:
        msg: |
          ============================================
          JupyterLab erfolgreich installiert!
          
          URL: http://node0.cloud.local:{{ jupyter_port }}
          Notebooks: {{ jupyter_data }}/notebooks
          
          Spark Master: spark://node1.cloud.local:7077
          ============================================

  handlers:
    - name: Restart JupyterLab
      ansible.builtin.systemd:
        name: jupyterlab
        state: restarted
        daemon_reload: yes
