---
# Monitoring Stack Installation (Prometheus + Grafana + Node Exporter)
#
# Verwendung:
#   ansible-playbook -i inventory.yml monitoring.yml
#

- name: Install Node Exporter on all nodes
  hosts: all
  vars:
    node_exporter_user: cloudadmin
    
  tasks:
    - name: Check if Node Exporter is already installed
      stat:
        path: /usr/local/bin/node_exporter
      register: node_exporter_installed

    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz
        mode: '0644'
      when: not node_exporter_installed.stat.exists

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp
        remote_src: yes
      when: not node_exporter_installed.stat.exists

    - name: Install Node Exporter
      copy:
        src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        remote_src: yes
      when: not node_exporter_installed.stat.exists

    - name: Clean up download
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/node_exporter.tar.gz
        - /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64
      when: not node_exporter_installed.stat.exists

    - name: Create Node Exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target
          
          [Service]
          User={{ node_exporter_user }}
          ExecStart=/usr/local/bin/node_exporter
          Restart=on-failure
          RestartSec=10
          
          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started

- name: Install Prometheus on monitoring node
  hosts: monitoring
  vars:
    prometheus_home: /opt/prometheus
    prometheus_data: /data/prometheus
    prometheus_user: cloudadmin
    
  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"
        mode: '0755'
      loop:
        - "{{ prometheus_home }}"
        - "{{ prometheus_data }}"

    - name: Check if Prometheus is already installed
      stat:
        path: "{{ prometheus_home }}/prometheus"
      register: prometheus_installed

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz
        mode: '0644'
      when: not prometheus_installed.stat.exists

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp
        remote_src: yes
      when: not prometheus_installed.stat.exists

    - name: Install Prometheus
      shell: |
        cp -r /tmp/prometheus-{{ prometheus_version }}.linux-amd64/* {{ prometheus_home }}/
        chown -R {{ prometheus_user }}:{{ prometheus_user }} {{ prometheus_home }}
      when: not prometheus_installed.stat.exists

    - name: Clean up download
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/prometheus.tar.gz
        - /tmp/prometheus-{{ prometheus_version }}.linux-amd64
      when: not prometheus_installed.stat.exists

    - name: Configure Prometheus
      copy:
        dest: "{{ prometheus_home }}/prometheus.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s
          
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
            
            - job_name: 'node'
              static_configs:
                - targets:
                    - 'node0.{{ domain }}:9100'
                    - 'node1.{{ domain }}:9100'
                    - 'node2.{{ domain }}:9100'
                    - 'node3.{{ domain }}:9100'
                    - 'node4.{{ domain }}:9100'
            
            - job_name: 'zookeeper'
              static_configs:
                - targets:
                    - 'node1.{{ domain }}:7070'
                    - 'node2.{{ domain }}:7070'
                    - 'node3.{{ domain }}:7070'
            
            - job_name: 'solr'
              metrics_path: '/solr/admin/metrics'
              params:
                type: ['prometheus']
              static_configs:
                - targets:
                    - 'node1.{{ domain }}:8983'
                    - 'node2.{{ domain }}:8983'
                    - 'node3.{{ domain }}:8983'
                    - 'node4.{{ domain }}:8983'

    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          After=network.target
          
          [Service]
          User={{ prometheus_user }}
          ExecStart={{ prometheus_home }}/prometheus \
            --config.file={{ prometheus_home }}/prometheus.yml \
            --storage.tsdb.path={{ prometheus_data }} \
            --web.listen-address=:9090
          Restart=on-failure
          RestartSec=10
          
          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started

    - name: Wait for Prometheus to start
      wait_for:
        port: 9090
        timeout: 30

- name: Install Grafana on monitoring node
  hosts: monitoring
  vars:
    grafana_user: cloudadmin
    
  tasks:
    - name: Add Grafana GPG key
      apt_key:
        url: https://apt.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      apt_repository:
        repo: "deb https://apt.grafana.com stable main"
        state: present
        filename: grafana

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Enable and start Grafana
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Wait for Grafana to start
      wait_for:
        port: 3000
        timeout: 30

    - name: Show Grafana info
      debug:
        msg: "Grafana running on http://{{ inventory_hostname }}:3000 (admin/admin)"
